/** Backend IPC channels (kebab-case) — Electron preload + Tauri zeus_invoke/zeus_send. */
export const ZEUS_INVOKE_CHANNELS = [
  'install-registry-get-status',
  'install-registry-set-enabled',
  'install-registry-send-now',
  'tcp-connect',
  'tcp-is-connected',
  'labelary-render',
  'handheld-is-running',
  'db-connect',
  'db-disconnect',
  'db-list-databases',
  'db-get-tables',
  'db-get-table-data',
  'db-execute-query',
  'db-get-primary-keys',
  'db-update-cell',
  'db-get-table-structure',
  'db-delete-row',
  'db-insert-row',
  'db-delete-rows',
  'db-export-table',
  'db-export-database-sql',
  'db-save-export-table-to-path',
  'db-save-export-database-sql-to-path',
  'db-save-export-database-csv-to-path',
  'db-import-rows',
  'db-get-database-schema',
  'sftp-connect',
  'sftp-disconnect',
  'sftp-readdir',
  'sftp-read-file',
  'sftp-write-file',
  'sftp-write-text-file',
  'sftp-mkdir',
  'sftp-rename',
  'sftp-unlink',
  'sftp-rmrf',
  'sftp-stat',
  'sftp-calculate-size',
  'sftp-set-attributes',
  'sftp-find-files',
  'sftp-find-cancel',
  'sftp-download-to-path',
  'sftp-upload-from-local',
  'sftp-copy-remote-file',
  'local-readdir',
  'local-write-file-base64',
  'local-path-parent',
  'net-scan-get-interfaces',
  'net-scan-start',
  'net-scan-cancel',
  'udp-discovery-start',
  'udp-discovery-stop',
  'udp-discovery-send-probe',
  'udp-discovery-is-running',
  'reader-discovery-start',
  'reader-discovery-cancel',
  'safe-store-set',
  'safe-store-get',
  'safe-store-delete',
  'admin-login',
  'admin-logout',
  'admin-is-authenticated',
  'get-auto-update-enabled',
  'set-auto-update-enabled',
  'get-api-config',
  'save-api-config',
  'itx-api-request',
  'ale-get-credential-meta',
  'ale-get-basic-auth-header',
  'ale-request',
  'ale-request-batch',
  'log-aggregator-run',
  'log-aggregator-show-output',
] as const

export const ZEUS_SEND_CHANNELS = [
  'tcp-disconnect',
  'tcp-send-tags',
  'tcp-cancel-send',
  'handheld-start',
  'handheld-stop',
  'handheld-send-epcs',
  'handheld-send-recipe',
  'handheld-cancel-send',
  'ocr-send',
  'custom-send',
  'check-for-update',
  'start-download',
  'quit-and-install',
  'shell-start',
  'shell-write',
  'shell-resize',
  'shell-kill',
] as const

export const ZEUS_EVENT_CHANNELS = [
  'tcp-connected',
  'tcp-disconnected',
  'tcp-error',
  'tcp-progress',
  'tcp-complete',
  'handheld-started',
  'handheld-stopped',
  'handheld-error',
  'handheld-progress',
  'handheld-complete',
  'ocr-success',
  'ocr-error',
  'custom-success',
  'custom-error',
  'db-export-progress',
  'net-scan-host',
  'net-scan-done',
  'net-scan-error',
  'udp-discovery-device',
  'udp-discovery-raw',
  'udp-discovery-started',
  'udp-discovery-stopped',
  'udp-discovery-error',
  'reader-discovery-host',
  'reader-discovery-done',
  'reader-discovery-error',
  'sftp-transfer-progress',
  'sftp-find-progress',
  'sftp-find-match',
  'shell-data',
  'shell-exit',
  'log-aggregator-progress',
] as const

export function channelToCamelMethod(channel: string): string {
  return channel.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase())
}

export function eventChannelToListenerMethod(channel: string): string {
  return (
    'on' +
    channel
      .split('-')
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join('')
  )
}

/** Dialog-backed invoke methods implemented in tauri-bridge (not zeus_invoke). */
export const TAURI_DIALOG_METHODS = new Set([
  'dbSaveExportTable',
  'dbSaveExportDatabaseSql',
  'dbSaveExportDatabaseCsv',
  'localPickFolder',
  'sftpDownloadSaveDialog',
  'logAggregatorPickZip',
  'logAggregatorPickOutput',
])

/** Browser dev mock stubs only. */
export const ELECTRON_ONLY_METHODS = new Set<string>([])
